### ISSUE TITLE
Error in initializing instances node1...n via Vagrant with vagrant 1.6.4

### ISSUE THREAD

**Issue by hagzag** [ripienaar/mcollective-vagrant#26]
The output of the Vagrant up command is below:

$ vagrant up --provider=virtualbox
Bringing machine 'middleware' up with 'virtualbox' provider...
Bringing machine 'node0' up with 'virtualbox' provider...
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
==> middleware: Importing base box 'centos_6_3_x86_64'...
==> middleware: Matching MAC address for NAT networking...
==> middleware: Setting the name of the VM: mcollective-vagrant_middleware_1426508928867_13183
==> middleware: Clearing any previously set network interfaces...
==> middleware: Preparing network interfaces based on configuration...
    middleware: Adapter 1: nat
    middleware: Adapter 2: hostonly
==> middleware: Forwarding ports...
    middleware: 22 => 2222 (adapter 1)
==> middleware: Running 'pre-boot' VM customizations...
==> middleware: Booting VM...
==> middleware: Waiting for machine to boot. This may take a few minutes...
    middleware: SSH address: 127.0.0.1:2222
    middleware: SSH username: vagrant
    middleware: SSH auth method: private key
    middleware: Warning: Connection timeout. Retrying...
==> middleware: Machine booted and ready!
==> middleware: Checking for guest additions in VM...
    middleware: The guest additions on this VM do not match the installed version of
    middleware: VirtualBox! In most cases this is fine, but in rare cases it can
    middleware: prevent things such as shared folders from working properly. If you see
    middleware: shared folder errors, please make sure the guest additions within the
    middleware: virtual machine match the version of VirtualBox you have installed on
    middleware: your host and reload your VM.
    middleware:
    middleware: Guest Additions Version: 4.2.6
    middleware: VirtualBox Version: 4.3
==> middleware: Setting hostname...
==> middleware: Configuring and enabling network interfaces...
==> middleware: Forcing shutdown of VM...
==> middleware: Destroying VM and associated drives...
==> middleware: Running cleanup tasks for 'shell' provisioner...
==> middleware: Running cleanup tasks for 'puppet' provisioner...
/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/guests/redhat/cap/configure_networks.rb:31:in `configure_networks_default': wrong number of arguments (1 for 2) (ArgumentError)
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/guests/redhat/cap/configure_networks.rb:19:in `configure_networks'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/capability_host.rb:111:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/capability_host.rb:111:in `capability'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/guest.rb:43:in `capability'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/network.rb:132:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:15:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/c5191707/.vagrant.d/gems/gems/vagrant-proxyconf-1.4.0/lib/vagrant-proxyconf/action/only_once.rb:21:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:160:in `handle'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:42:in `block in call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/environment.rb:474:in `lock'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:41:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/c5191707/.vagrant.d/gems/gems/vagrant-proxyconf-1.4.0/lib/vagrant-proxyconf/action/only_once.rb:21:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/c5191707/.vagrant.d/gems/gems/vagrant-omnibus-1.4.1/lib/vagrant-omnibus/action/install_chef.rb:38:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/c5191707/.vagrant.d/gems/gems/vagrant-proxyconf-1.4.0/lib/vagrant-proxyconf/action/only_once.rb:21:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/match_mac_address.rb:16:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/import.rb:32:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/builder.rb:116:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/action/runner.rb:66:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/machine.rb:196:in `action_raw'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/machine.rb:173:in `block in action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/environment.rb:474:in `lock'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/machine.rb:161:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/machine.rb:161:in `action'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by hagzag** [comment]
Upgrading Vagrant to 1.7.2 seemed to solve the issue.
